assets/reviews.css
assets/reviews.js
snippets/product-preview.liquid
styles/reviews.scss

Fix > Show reviews only if any

---

assets/general-review.css
assets/product.css
assets/product.js
assets/reviews-count.js
sections/product.liquid
snippets/general-review.liquid
snippets/product-home.liquid
snippets/product-images-showcase.liquid
snippets/single-product.liquid
styles/general-review.scss
styles/product.scss

[DOT-7338](https://nextmediama.atlassian.net/browse/DOT-7338)
this is just the part 1 of the product page integration
[DOT-7338]: https://youcanshop.atlassian.net/browse/DOT-7338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOT-7338 : COD theme > Product Page > integrate the head page part 1

---

assets/product-listing.css
assets/queries-handler.js
locales/ar.default.json
locales/en.json
locales/fr.json
sections/main-collection.liquid
snippets/main-pagination.liquid
snippets/main-sort.liquid
styles/product-listing.scss
templates/index.json

[DOT-7420](https://nextmediama.atlassian.net/browse/DOT-7420)
[DOT-7420]: https://youcanshop.atlassian.net/browse/DOT-7420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOT-7420: Integrate the new pagination and sorting 

---

assets/featured-products.css
assets/hot-featured-products.css
assets/main.css
assets/navbar.css
assets/product-column.css
assets/product-listing.css
assets/product-slider.css
sections/desktop-slider.liquid
sections/featured-product-slider.liquid
sections/featured-products.liquid
sections/main-navbar.liquid
sections/multi-column.liquid
snippets/countdown.liquid
snippets/product-home.liquid
snippets/product-slider.liquid
snippets/single-product.liquid
styles/featured-products.scss
styles/hot-featured-products.scss
styles/main.scss
styles/navbar.scss
styles/product-column.scss
styles/product-listing.scss
styles/product-slider.scss
templates/index.json

[YSHOP2-90](https://youcanshop.atlassian.net/browse/YSHOP2-90)
[YSHOP2-90]: https://youcanshop.atlassian.net/browse/YSHOP2-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-90: COD-Theme > Update the home page with the latest changes from the design

---

assets/footer.css
assets/main.css
assets/pages.css
sections/main-page.liquid
sections/multi-column.liquid
styles/footer.scss
styles/main.scss
styles/pages.scss
templates/page.json

[YSHOP2-104](https://youcanshop.atlassian.net/browse/YSHOP2-104)
[YSHOP2-104]: https://youcanshop.atlassian.net/browse/YSHOP2-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-104: COD-Theme > Integrate the contact us and about us pages

---

assets/cart.css
assets/cart.js
sections/main-cart.liquid
styles/cart.scss

DARK: update the sum and the price of all the products on the cart page

---

assets/product.js

[YSHOP2-135](https://youcanshop.atlassian.net/browse/YSHOP2-135
https://user-images.githubusercontent.com/108662497/223696452-2691d086-51d9-486e-ab49-0b5cd90d73ec.mov
Fix the product page when the user select variant 
[DOT-135]: https://youcanshop.atlassian.net/browse/DOT-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[YSHOP2-135]: https://youcanshop.atlassian.net/browse/YSHOP2-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-135: COD-Theme > Product Page show the product image when the user select the color varianats

---

assets/accordion.css
assets/countdown.css
assets/product.css
assets/reviews-count.js
assets/reviews.css
assets/reviews.js
locales/ar.default.json
sections/feature-products-by-category.liquid
sections/product-reviews.liquid
sections/product.liquid
snippets/accordion.liquid
snippets/countdown.liquid
snippets/general-review.liquid
snippets/head-config.liquid
snippets/product-home.liquid
snippets/reviews.liquid
snippets/single-product.liquid
styles/accordion.scss
styles/countdown.scss
styles/product.scss
styles/reviews.scss
templates/product.json

[YSHOP2-130](https://youcanshop.atlassian.net/browse/YSHOP2-130)
[YSHOP2-130]: https://youcanshop.atlassian.net/browse/YSHOP2-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-130 : COD theme > Product page > UI enhancements

---

assets/product-card.css
assets/product.js
snippets/product-card.liquid
styles/product-card.scss

DARK:  Show sticky product price currency

---

assets/express-checkout.css
assets/product.js
snippets/single-product.liquid
snippets/sticky-checkout.liquid
styles/express-checkout.scss

Dark: Product page > Fix sticky checkout responsiveness

---

assets/reviews.js
snippets/reviews.liquid
styles/reviews.scss

-  [ ] visit any product page with reviews, and test it

Code Refactoring: Reviews

---

assets/accordion.js
assets/product-quantity-input.js

Code Refactoring: Accordion & product-quantity-input

---

snippets/single-product.liquid

Fix the product slider on mobile

---

assets/product.js
snippets/single-product.liquid

DARK : fix product page nullable errors in console log

---

assets/main.css

[YSHOP2-259](https://youcanshop.atlassian.net/browse/YSHOP2-259)
[YSHOP2-259]: https://youcanshop.atlassian.net/browse/YSHOP2-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-259: Fixing the theme preview

---

sections/feature-products-by-category.liquid
sections/featured-products.liquid

[YSHOP2-253](https://youcanshop.atlassian.net/browse/YSHOP2-253)
[YSHOP2-253]: https://youcanshop.atlassian.net/browse/YSHOP2-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-253: Removing the countdown settings from the List of Products section

---

.github/pull_request_template.md
assets/navbar.css
styles/navbar.scss

[YSHOP2-294](https://youcanshop.atlassian.net/browse/YSHOP2-294)
[YSHOP2-294]: https://youcanshop.atlassian.net/browse/YSHOP2-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-294: [Navbar] Setting "Cart badge color" not used

---

snippets/product-home.liquid

Fix money filter bug on product column

fix: money filter bug on product column

---

sections/main-footer.liquid

[YSHOP2-302](https://youcanshop.atlassian.net/browse/YSHOP2-302)
[YSHOP2-302]: https://youcanshop.atlassian.net/browse/YSHOP2-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-302: change social media setting label

---

assets/notice-bar.css
styles/notice-bar.scss

[YSHOP2-301](https://youcanshop.atlassian.net/browse/YSHOP2-301)
[YSHOP2-301]: https://youcanshop.atlassian.net/browse/YSHOP2-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-301: mobile notice bar height alignment

---

sections/featured-product-slider.liquid

[YSHOP2-291](https://youcanshop.atlassian.net/browse/YSHOP2-291)
[YSHOP2-291]: https://youcanshop.atlassian.net/browse/YSHOP2-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-291: Theme 1 > Products slider: Changing the background color is not applied to the background

---

sections/featured-product-slider.liquid
templates/index.json

[YSHOP2-312](https://youcanshop.atlassian.net/browse/YSHOP2-312)
[YSHOP2-312]: https://youcanshop.atlassian.net/browse/YSHOP2-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-312: Products Slider > The text color is not applied properly

---

assets/navbar.css
styles/navbar.scss

[YSHOP2-295](https://youcanshop.atlassian.net/browse/YSHOP2-295)
[YSHOP2-295]: https://youcanshop.atlassian.net/browse/YSHOP2-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-295: [Navbar] Links font weight doesn't seems to be used

---

sections/main-navbar.liquid

[YSHOP2-295](https://youcanshop.atlassian.net/browse/YSHOP2-295)
[YSHOP2-295]: https://youcanshop.atlassian.net/browse/YSHOP2-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-295: Import navbar font

---

assets/product.css
styles/product.scss

[YSHOP2-321](https://youcanshop.atlassian.net/browse/YSHOP2-321)
check on different browser like safari to verify for the single product width
[YSHOP2-321]: https://youcanshop.atlassian.net/browse/YSHOP2-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-321: Single Product > On mobile, the product image and the variants take half of the screen each

---

sections/featured-product-slider.liquid
snippets/product-slider.liquid

[YSHOP2-315](https://youcanshop.atlassian.net/browse/YSHOP2-315)
[YSHOP2-315]: https://youcanshop.atlassian.net/browse/YSHOP2-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-315: Products Slider > Banner settings are not functioning

---

sections/feature-products-by-category.liquid

[YSHOP2-328](https://youcanshop.atlassian.net/browse/YSHOP2-328)
[YSHOP2-328]: https://youcanshop.atlassian.net/browse/YSHOP2-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-328: [Feature products by category] Padding top seems to have extra padding that the one configured

---

assets/express-checkout.css
sections/product.liquid
snippets/express-checkout.liquid
snippets/single-product.liquid
styles/express-checkout.scss
styles/main.scss
templates/index.json

[YSHOP2-335](https://youcanshop.atlassian.net/browse/YSHOP2-335)
[YSHOP2-335]: https://youcanshop.atlassian.net/browse/YSHOP2-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-335 : COD v1 Express checkout bloc - Gap between input fields settings not working

---

assets/footer.css
assets/main.css
sections/main-footer.liquid
styles/footer.scss
styles/main.scss

[YSHOP2-310](https://youcanshop.atlassian.net/browse/YSHOP2-310)
[YSHOP2-310]: https://youcanshop.atlassian.net/browse/YSHOP2-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-310 : COD v1 > [Footer] Dissociate the social media from the mentions

---

snippets/product-home.liquid

DARK : COD V1 > Product column section > fix compare price value error

---

assets/reviews-count.js
assets/reviews.js
sections/product-reviews.liquid
sections/product.liquid
snippets/product-home.liquid
snippets/reviews.liquid

DARK : COD v1 > fix the visibility of reviews in Product & home pages

---

assets/main.css
sections/product.liquid
snippets/add-to-cart.liquid
styles/main.scss

[YSHOP2-354](https://youcanshop.atlassian.net/browse/YSHOP2-354)
[YSHOP2-354]: https://youcanshop.atlassian.net/browse/YSHOP2-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-354 : Single product > Add to card size is small 

---

assets/stock.css
sections/product.liquid
snippets/single-product.liquid
snippets/stock.liquid
styles/stock.scss

[YSHOP2-356](https://youcanshop.atlassian.net/browse/YSHOP2-356)
[YSHOP2-356]: https://youcanshop.atlassian.net/browse/YSHOP2-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-356 : Single product > Stock > set default limit value

---

assets/product-column.css
sections/main-video.liquid
styles/product-column.scss
templates/index.json

[YSHOP2-350](https://youcanshop.atlassian.net/browse/YSHOP2-350)
[YSHOP2-350]: https://youcanshop.atlassian.net/browse/YSHOP2-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-350: Video > The video section should have bottom and top padding settings

---

sections/desktop-slider.liquid

[YSHOP2-306](https://youcanshop.atlassian.net/browse/YSHOP2-306)
[YSHOP2-306]: https://youcanshop.atlassian.net/browse/YSHOP2-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-306: [Slider] On Overlay Background Color change, keep the transparency level previously selected

---

config/settings_data.json

DARK: update theme settings

---

sections/main-video.liquid

DARK: fix video container

---

assets/reviews-count.js
snippets/general-review.liquid

DARK: single product ratings

---

assets/add-to-cart.js
assets/cart-drawer.css
styles/cart-drawer.scss

[YSHOP2-387](https://youcanshop.atlassian.net/browse/YSHOP2-387)
[YSHOP2-387]: https://youcanshop.atlassian.net/browse/YSHOP2-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-387: Cart drawer doesn’t have currency 

---

templates/index.json

update index.json settings

---

sections/feature-products-by-category.liquid
templates/index.json

[YSHOP2-377](https://youcanshop.atlassian.net/browse/YSHOP2-377)
[YSHOP2-377]: https://youcanshop.atlassian.net/browse/YSHOP2-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-377: Section initial background/text color is not getting applied

---

package.json

chore(package): Update CLI dev command

---

sections/feature-products-by-category.liquid

[YSHOP2-378](https://youcanshop.atlassian.net/browse/YSHOP2-378)
[YSHOP2-378]: https://youcanshop.atlassian.net/browse/YSHOP2-378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Theme QA > add dedicated setting for title text color

---

sections/feature-products-by-category.liquid

[YSHOP2-376](https://youcanshop.atlassian.net/browse/YSHOP2-376)
[YSHOP2-376]: https://youcanshop.atlassian.net/browse/YSHOP2-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Theme QA > Remove background image setting

---

sections/multi-column.liquid

Multi-column block description should accept text not html

---

sections/multi-column.liquid

[YSHOP2-396](https://youcanshop.atlassian.net/browse/YSHOP2-396)
[YSHOP2-396]: https://youcanshop.atlassian.net/browse/YSHOP2-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-396 : Multi-column Buttons to be removed

---

sections/multi-column.liquid

[YSHOP2-398](https://youcanshop.atlassian.net/browse/YSHOP2-398)
[YSHOP2-398]: https://youcanshop.atlassian.net/browse/YSHOP2-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-398: Fix default Columns count

---

config/settings_schema.json
sections/desktop-slider.liquid
sections/featured-product-slider.liquid
sections/featured-products.liquid
sections/multi-column.liquid
sections/product-column.liquid

[YSHOP2-389](https://youcanshop.atlassian.net/browse/YSHOP2-389)
[YSHOP2-389]: https://youcanshop.atlassian.net/browse/YSHOP2-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-389 : Naming conventions, first letter uppercase only (Part 1)

---

assets/notice-bar.css
sections/notice-bar.liquid
styles/notice-bar.scss

[YSHOP2-400](https://youcanshop.atlassian.net/browse/YSHOP2-400)
[YSHOP2-401](https://youcanshop.atlassian.net/browse/YSHOP2-401)
[YSHOP2-400]: https://youcanshop.atlassian.net/browse/YSHOP2-400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[YSHOP2-401]: https://youcanshop.atlassian.net/browse/YSHOP2-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Theme QA > Fix Notice bar

---

snippets/single-product.liquid

[YSHOP2-403](https://youcanshop.atlassian.net/browse/YSHOP2-403)
[YSHOP2-403]: https://youcanshop.atlassian.net/browse/YSHOP2-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-403: Express checkout button

---

sections/main-navbar.liquid
snippets/head-config.liquid

[YSHOP2-410](https://youcanshop.atlassian.net/browse/YSHOP2-410)
[YSHOP2-410]: https://youcanshop.atlassian.net/browse/YSHOP2-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-410: "Show navbar shadow” is not working

---

config/settings_schema.json

[YSHOP2-409](https://youcanshop.atlassian.net/browse/YSHOP2-409)
[YSHOP2-409]: https://youcanshop.atlassian.net/browse/YSHOP2-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-409: update the settings naming

---

config/settings_data.json
sections/main-footer.liquid
sections/main-navbar.liquid

[YSHOP2-407](https://youcanshop.atlassian.net/browse/YSHOP2-407)
[YSHOP2-407]: https://youcanshop.atlassian.net/browse/YSHOP2-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-407: Option to hide the nav-bar

---

sections/feature-products-by-category.liquid
sections/featured-collections.liquid
sections/featured-product-slider.liquid
sections/featured-products.liquid
sections/main-express-checkout.liquid
sections/main-navbar.liquid
sections/main-video.liquid
sections/multi-column.liquid
sections/notice-bar.liquid
sections/product-column.liquid
sections/product.liquid

[YSHOP2-389](https://youcanshop.atlassian.net/browse/YSHOP2-389)
[YSHOP2-389]: https://youcanshop.atlassian.net/browse/YSHOP2-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-389 : Naming conventions, first letter uppercase only (part 2)

---

sections/desktop-slider.liquid
sections/featured-product-slider.liquid

[YSHOP2-414](https://youcanshop.atlassian.net/browse/YSHOP2-414)
[YSHOP2-414]: https://youcanshop.atlassian.net/browse/YSHOP2-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-414: Enlarging Mobile & Desktop Settings text

---

assets/helper.js

[YSHOP2-325](https://youcanshop.atlassian.net/browse/YSHOP2-325)
[YSHOP2-325]: https://youcanshop.atlassian.net/browse/YSHOP2-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-325 : Products Slider > Display countdown even if time runs out

---

assets/collection-listing.css
assets/navbar.css
assets/product-column.css
assets/product-listing.css
sections/main-navbar.liquid
sections/product.liquid
snippets/head-config.liquid
snippets/product-images-showcase.liquid
snippets/single-product.liquid
styles/collection-listing.scss
styles/navbar.scss
styles/product-column.scss
styles/product-listing.scss
templates/index.json

update COD Theme settings

---

sections/desktop-slider.liquid
sections/featured-product-slider.liquid

remove icons from settings

---

assets/cart.js
sections/main-collection.liquid
snippets/general-review.liquid
snippets/head-config.liquid
snippets/reviews.liquid

DARK : fix console log errors for COD v1

---

assets/reviews-count.js
sections/product-reviews.liquid
sections/product.liquid
snippets/head-config.liquid
snippets/product-home.liquid
snippets/reviews.liquid

[SHOP2-474](https://youcanshop.atlassian.net/browse/SHOP2-474)

SHOP2-474: COD v1 - Update `averageRating` to product template and product section

---

assets/helper.js

[YSHOP2-500](https://youcanshop.atlassian.net/browse/YSHOP2-500)
[YSHOP2-500]: https://youcanshop.atlassian.net/browse/YSHOP2-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-500 : COD V1 > Countdown functionality triggering an infinite loop making the web page crush

---

assets/cart.js
assets/main.css
assets/main.js
assets/queries-handler.js
locales/ar.default.json
sections/main-cart.liquid
sections/main-search.liquid
styles/main.scss

[YSHOP2-505](https://youcanshop.atlassian.net/browse/YSHOP2-505)
[YSHOP2-505]: https://youcanshop.atlassian.net/browse/YSHOP2-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-505 : Search page > fix UI bugs

---

sections/featured-products.liquid
sections/multi-column.liquid
templates/index.json

[YSHOP2-595](https://youcanshop.atlassian.net/browse/YSHOP2-595)
[YSHOP2-595]: https://youcanshop.atlassian.net/browse/YSHOP2-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-595 : COD v1 > Default text colors for themes

---

assets/featured-collections.css
sections/featured-collections.liquid
sections/featured-product-slider.liquid
sections/featured-products.liquid
styles/featured-collections.scss

[YSHOP2-609](https://youcanshop.atlassian.net/browse/YSHOP2-609)
[YSHOP2-609]: https://youcanshop.atlassian.net/browse/YSHOP2-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-609: As a seller, I should be guided on the images sizes

---

sections/desktop-slider.liquid
snippets/slider.liquid

[YSHOP2-608](https://youcanshop.atlassian.net/browse/YSHOP2-608)
[YSHOP2-608]: https://youcanshop.atlassian.net/browse/YSHOP2-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-608 : COD v1 > Slider - Remove arrows when one image is used 

---

assets/product.js

DARK : fix product price in COD theme v1

---

assets/subCategory.css
sections/main-collection.liquid
snippets/subCategory.liquid
styles/subCategory.scss

[YSHOP2-702](https://youcanshop.atlassian.net/browse/YSHOP2-702)
[YSHOP2-702]: https://youcanshop.atlassian.net/browse/YSHOP2-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-702: Display the subcategories on the COD themes

---

assets/add-to-cart.js
assets/cart-drawer.css
assets/cart.css
assets/cart.js
assets/main.css
assets/main.js
sections/main-cart.liquid
styles/cart-drawer.scss
styles/cart.scss
styles/main.scss

[YSHOP2-692](https://youcanshop.atlassian.net/browse/YSHOP2-692)
[YSHOP2-692]: https://youcanshop.atlassian.net/browse/YSHOP2-692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-692 :COD theme V1 > cart page and cart drawer bugs

---

assets/product.css
styles/product.scss

[YSHOP2-711](https://youcanshop.atlassian.net/browse/YSHOP2-711)
[YSHOP2-711]: https://youcanshop.atlassian.net/browse/YSHOP2-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-711: Themes Bugs

---

sections/desktop-slider.liquid
templates/index.json
templates/page.json

[YSHOP2-721](https://youcanshop.atlassian.net/browse/YSHOP2-721)
[YSHOP2-721]: https://youcanshop.atlassian.net/browse/YSHOP2-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-721: Default theme settings - Theme 1

---

templates/product.json

[YSHOP2-719](https://youcanshop.atlassian.net/browse/YSHOP2-719)
[YSHOP2-719]: https://youcanshop.atlassian.net/browse/YSHOP2-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-719 : Express checkout stays sticky - theme 1

---

assets/navbar.css
styles/navbar.scss

[YSHOP2-722](https://youcanshop.atlassian.net/browse/YSHOP2-722)
[YSHOP2-722]: https://youcanshop.atlassian.net/browse/YSHOP2-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-722 : Mobile navbar not displaying correctly for theme 1

---

config/settings_schema.json

[YSHOP2-701](https://youcanshop.atlassian.net/browse/YSHOP2-701)
[YSHOP2-701]: https://youcanshop.atlassian.net/browse/YSHOP2-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-701 : Adding text on customizing the checkout color in the global settings - theme 1

---

sections/featured-products.liquid
snippets/product-preview.liquid
templates/index.json

[YSHOP2-790](https://youcanshop.atlassian.net/browse/YSHOP2-790)
[YSHOP2-790]: https://youcanshop.atlassian.net/browse/YSHOP2-790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-790 : Banner settings are not applied in the featured products section

---

assets/footer.css
sections/main-footer.liquid
styles/footer.scss

[YSHOP2-800](https://youcanshop.atlassian.net/browse/YSHOP2-800)
[YSHOP2-800]: https://youcanshop.atlassian.net/browse/YSHOP2-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-800: Footer - When no social media icons and no caption, collapse the empty space

---

locales/en.json
locales/fr.json

[YSHOP2-836](https://youcanshop.atlassian.net/browse/YSHOP2-836)
[YSHOP2-836]: https://youcanshop.atlassian.net/browse/YSHOP2-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-836: Update and complete translation files

---

assets/thankyou.css
sections/thankyou.liquid
styles/thankyou.scss

[YSHOP2-863](https://youcanshop.atlassian.net/browse/YSHOP2-863)
[YSHOP2-863]: https://youcanshop.atlassian.net/browse/YSHOP2-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-863: Upload icon in thank you page - Theme 1

---

snippets/accordion.liquid
snippets/single-product.liquid
templates/product.json

Accorion styling not working in theme editor
This update will also be included in COD theme 2

DARK : theme editor > Section single product > fix accordion styling

---

assets/cart-drawer.css
assets/navbar.css
sections/main-collection.liquid
sections/main-upsell.liquid
snippets/add-to-cart.liquid
styles/cart-drawer.scss
styles/navbar.scss

-  Fix (upsell, collection) page when the main body is empty
- Fix add-to-cart button padding to be similar to the padding of the express checkout button 
- Fix The issue of the X button on the LTR direction of the Cart drawer
- Fix z-index of the search bar when we have sticky checkout

DARK: Theme 1 > fix minor bugs

---

assets/add-to-cart.js
assets/cart-drawer.css
assets/navbar.css
styles/cart-drawer.scss
styles/navbar.scss

DARK: fix overlay issue with the navbar

---

snippets/countdown.liquid
snippets/single-product.liquid

DARK: fix the slider issue when the single product section is on the home page

---

assets/express-checkout.css
assets/main.js
assets/navbar.css
assets/product.css
assets/product.js
sections/main-navbar.liquid
snippets/single-product.liquid
styles/express-checkout.scss
styles/navbar.scss
styles/product.scss

[YSHOP2-986](https://youcanshop.atlassian.net/browse/YSHOP2-986)
Issues are described in the ticket with screenshots
[YSHOP2-986]: https://youcanshop.atlassian.net/browse/YSHOP2-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-986: theme 1 > Themes bugs for (single product section & navbar section)

---

assets/cart.js
locales/en.json
locales/fr.json

DARK: theme 1 > coupon > add missing content

---

assets/dropdown-menu.js
assets/queries-handler.js
snippets/product-variants.liquid

[YSHOP2-1031](https://youcanshop.atlassian.net/browse/YSHOP2-1031)
[YSHOP2-1031]: https://youcanshop.atlassian.net/browse/YSHOP2-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1031: COD themes > theme 1 > dropdown menu bugs

---

sections/desktop-slider.liquid
snippets/slider.liquid
styles/featured-products.scss

add changes to main back

---

styles/featured-products.scss

[YSHOP2-1279](https://youcanshop.atlassian.net/browse/YSHOP2-1279)
[YSHOP2-1279]: https://youcanshop.atlassian.net/browse/YSHOP2-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1279: Theme 1 > Right & left spacing for featured products section

---

sections/featured-products.liquid

https://youcan-shop.slack.com/archives/C04BDG9HEB1/p1711499774678319
-  [ ]  Select featured products section
-  [ ] Try to add more than 25 product block

DARK: featured products > add max blocks
